# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b34830fd01dbae8d13ca0d3fc8fa7800613ac45414b9aa3e61f88c73315a3ed2c2d35de8316bcb9b31fad9472117b2564a3fad77a49fbc13d095c7b4cc12949

test:
  secret_key_base: d29a9f25c3fe582e3b5a0c20f812140d9f6a5a4b79b45633a558b29d2b84c9fd721d596324a34abec79ce036a6b9af97a074e77941861d20ae8a28508ca3240c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
